### ISSUE TITLE
Problem when adding filter 'air_reactions_reaction_item'

### ISSUE THREAD

**Issue by hoandt** [digitoimistodude/air-reactions#4]
Hi,

I don't know if it's just me or not, but when I do 

```
add_filter( 'air_reactions_reaction_item', function( (string) $output, (string) $key, (array) $item ) {
  // Do something
  return $output;
});
```
it causes error. But when I pass only 1 argument and not declare the argument type in parentheses, it works. 
```
add_filter( 'air_reactions_reaction_item', function ($output) {
      $output = 'something';
      return $output;
 });
```

**Comment by Niq1982** [comment]
Ah, the parameter amount is missing from the example function call. Try adding priority and params at the end.

```
add_filter( 'air_reactions_reaction_item', function ($output, $key, $item) {
      $output = 'something';
      return $output;
 }, 10, 3 );
```

**Comment by hoandt** [comment]
> Ah, the parameter amount is missing from the example function call. Try adding priority and params at the end.
> 
> ```
> add_filter( 'air_reactions_reaction_item', function ($output, $key, $item) {
>       $output = 'something';
>       return $output;
>  }, 10, 3 );
> ```

It works! Thank you @Niq1982
